module.exports = {
  MOVIE_COMMENTS_RECEIVED: "MOVIE_COMMENTS_RECEIVED",
  ACTOR_COMMENTS_RECEIVED: "ACTOR_COMMENTS_RECEIVED",
  ACTOR_COMMENT_RECEIVED: "ACTOR_COMMENT_RECEIVED",
  MOVIE_COMMENT_RECEIVED: "MOVIE_COMMENT_RECEIVED"
}
